apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sangay-deploy
  name: sangay-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sangay-deploy
  template:
    metadata:
      labels:
        app: sangay-deploy
    spec:
      containers:
      - image: sangaywangmo/bhutan:27
        name: pet
