apiVersion: v1
kind: Service
metadata:
  labels:
    app: sangay-deploy
  name: sangay-svc
  #namespace: pet
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sangay-deploy
  type: NodePort
